# -*- coding: utf-8 -*-
"""sql_generator

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10JvVzrRfpiomhp0_19uUfEIL8ZmKgz-Y
"""


import torch

def generate_sql(prompt, model, tokenizer, max_new_tokens=500):
    """
    Generate SQL query from a natural language prompt.
    """
    inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
    outputs = model.generate(**inputs, max_new_tokens=max_new_tokens)
    sql_query = tokenizer.decode(outputs[0], skip_special_tokens=True)
    return sql_query



import re

def extract_sql(text):
    """
    Extract SQL code between ```sql ... ``` markers if found.
    If not found, return the full text.
    """
    pattern = r"```(.*?)\n(.*?)(```|$)"
    matches = re.findall(pattern, text, re.DOTALL)
    
    if matches:
        clean_sql = matches[0][1].strip()
        #return sql_code
    else:
        return text.strip()

    sql_code = clean_sql.replace('\n', ' ').replace('\t', ' ')
    sql_code = re.sub(r'\s+', ' ', sql_code)
    return sql_code